version: '3'

services:
  django-app:
    image: django-app
    restart: always

    expose:
      - 80

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django-app
