apiVersion: v1
kind: Service
metadata:
  name: graduation-app
  namespace: python-app
  labels:
    app: graduation-app
spec:
  selector:
    app: graduation-app
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: LoadBalancer
  ports:
  - port: 8000 
    targetPort: 8000